name: Testing workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run Dev Build'
        required: true
        type: boolean

jobs:
  run_if_push:
    runs-on: ubuntu-latest
    if: ${{ ! inputs.tags }}
    steps:
      - run: echo "Hello, Push!"

  run_always:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, Always!"    

  run_if_dispatch:
    runs-on: ubuntu-latest
    if: ${{ inputs.tags }}
    steps:
      - run: echo "Hello, Dispatch!"
  
  run_if_dispatch_in_bash:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.tag }}
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Get tag
        id: vars
        run: >-
          if [[ "${{ inputs.tags }}" == "true" ]]; then
            echo "tag=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT
            echo "${{ steps.vars.outputs.tag }}"
          else
            echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
            echo "${{ steps.vars.outputs.tag }}"
          fi