name: Testing workflows

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  run_if_not_dispatch:
    runs-on: ubuntu-latest
    if: ${{ ! github.event.workflow_dispatch }}
    steps:
      - run: echo "Hello, Push!"

  run_if_dispatch:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_dispatch }}
    steps:
      - run: echo "Hello, Dispatch!"    
      