name: Testing workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags to deploy'
        required: true
        type: boolean


jobs:
  run_if_push:
    runs-on: ubuntu-latest
    if: ${{ ! inputs.tags }}
    steps:
      - run: echo "Hello, Push!"

  run_if_dispatch:
    runs-on: ubuntu-latest
    if: ${{ inputs.tags }}
    steps:
      - run: echo "Hello, Dispatch!"    
      