name: Testing workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      dev_version:
        description: 'DEV Build version (postfix)'
        required: true
        type: string

jobs:
  build_bool_output:
    runs-on: ubuntu-latest
    if: always()
    outputs:
      dev_version: ${{ steps.dev-bool.outputs.dev_version }}
    steps:
      - name: Set output
        id: dev-bool
        run: >-
          if [[ -n "${{ inputs.dev_version }}" ]]; then
            echo "dev_version=true" >> $GITHUB_OUTPUT
          else
            echo "dev_version=false" >> $GITHUB_OUTPUT
          fi  

  run_if_push:
    needs: build_bool_output
    runs-on: ubuntu-latest
    if: ${{ ! needs.build_bool_output.outputs.dev_version }}
    steps:
      - run: echo "Hello, Push!"

  run_always:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, Always!"    

  run_if_dispatch:
    needs: build_bool_output
    runs-on: ubuntu-latest
    if: ${{ needs.build_bool_output.outputs.dev_version }}
    steps:
      - run: echo "Hello, Dispatch!"
  
  run_if_dispatch_in_bash:
    needs: build_bool_output
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Get tag
        id: vars
        run: >-
          if [[ "${{ needs.build_bool_output.outputs.dev_version }}" == "true" ]]; then
            echo "input is true"
          else
            echo "input is false"
          fi